[package]
name = "room-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
freenet-stdlib = { path = "../../stdlib/rust" }
ciborium = "0.2.2"

[features]
default = ["freenet-main-contract"]
#contract = ["freenet-stdlib/contract"]
freenet-main-contract = []
#trace = ["freenet-stdlib/trace"]