[package]
name = "room-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
freenet-stdlib.workspace = true
common.workspace = true
serde.workspace = true
ciborium.workspace = true
itertools.workspace = true