[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
# Serialization
ciborium.workspace = true
serde.workspace = true

# Cryptography
ed25519-dalek.workspace = true
blake3.workspace = true
x25519-dalek.workspace = true

# Utilities
rand.workspace = true
itertools.workspace = true
base64.workspace = true
once_cell.workspace = true
data-encoding.workspace = true

# Internal dependencies
freenet-scaffold.workspace = true
freenet-scaffold-macro.workspace = true

[dev-dependencies]
rand.workspace = true
