[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium.workspace = true
serde.workspace = true
ed25519-dalek.workspace = true
blake3.workspace = true
itertools = "0.13.0"
rand = "0.8.5"
base64 = "0.22.1"
once_cell = "1.18.0"

[dev-dependencies]
rand = "0.8.5"
