[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
# Serialization
ciborium.workspace = true
serde.workspace = true

# Cryptography
ed25519-dalek.workspace = true
blake3.workspace = true
x25519-dalek = "2.0.0"

# Utilities
rand.workspace = true
itertools = "0.13.0"
base64 = "0.22.1"
once_cell = "1.18.0"
data-encoding = "2.3.3"

# Internal dependencies
freenet-scaffold = { path = "../scaffold" }
freenet-scaffold-macro = { path = "../scaffold-macro" }

[dev-dependencies]
rand = "0.8.5"
