[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium.workspace = true
serde.workspace = true
ed25519-dalek.workspace = true
blake3.workspace = true
rand.workspace = true
itertools = "0.13.0"
base64 = "0.22.1"
once_cell = "1.18.0"
freenet-scaffold = { path = "../scaffold" }
freenet-scaffold-macro = { path = "../scaffold-macro" }
data-encoding = "2.3.3"
x25519-dalek = "2.0.0"  # Add this line

[dev-dependencies]
rand = "0.8.5"
